### ISSUE TITLE
Why do I need this, or want to do this?

### ISSUE THREAD

**Issue by zazz-ops** [payloadcms/plugin-relationship-object-ids#3]
My assumption was that Payload handled any type conversion for relationship IDs itself.

What is the use case for this plugin?

Are there issues with mismatched types on relationship IDs that Payload core doesn't handle to warrant this plugin?

**Comment by nathanclevenger** [comment]
@zazz-ops  The ObjectID is a more efficient binary data type that is 24 hex characters long, but is only stored as 12 bytes vs the 24 bytes that this takes up as a string.  

The `_id` on an object is the more efficient ObjectId, but all references in Payload relationship fields are by default stored as strings.  Not only is this less efficient, but it makes `$lookup` aggregations directly in Mongo a lot more complex because the strings must be converted to ObjectIDs.

For most payload small Payload apps, this isn't a big deal ... but if you get large databases with anything over millions of documents and relationships (our databases have collections with hundreds of millions of Mongo documents and relationships), then this is a really big deal.  

That said, this plugin is currently broken for Payload 2.0, but I'm eagerly awaiting its update as this capability is important to our use cases.

**Comment by zazz-ops** [comment]
Thanks for the excellent information, Nathan. I’m surprised to hear that any _id was ever stored as a string. I ran into this same issue when building a bespoke CMS backed by Mongo.

**Comment by alexrindone** [comment]
I actually don't think you need a plugin for this...mongoose has the ability to do something like this:

`const id = new mongoose.Types.ObjectId(idAsString);`

So I would look into how this function works in mongoose if you don't want to import that package, or you can import and use it this way, with a field level beforeChange hook. This will automatically make it so that your string that is an id is converted to an ObjectId before being stored in the database.

**Comment by nathanclevenger** [comment]
@alexrindone But payload is by default storing references as a string not ObjectId ... which is the entire point of this plugin so that they are stored as ObjectId and not a string ...

**Comment by alexrindone** [comment]
Yeah, it appears that you can't override that either. I would have thought that you could override the way it's stored if you did something within a beforeChange hook. I attempted to do what I outlined, and it actually converted it back oddly enough.

**Comment by jmikrut** [comment]
Just chiming in here – I believe this plug-in is now fully functional with 2.0, but the team and I are going to double check this tomorrow and report back. I think that the discussion here should be suitable for answering the original issue question of why this is needed though so I am going to close it

**Comment by zazz-ops** [comment]
@jmikrut Is this plugin fully functional? I can't manage to import it, and I can't install it via npm. So I can't even get it into my codebase let alone test if it's functional.
